/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinasiRouteImport } from './routes/destinasi'
import { Route as CaraPemesananRouteImport } from './routes/cara-pemesanan'
import { Route as ArmadaRouteImport } from './routes/armada'
import { Route as IndexRouteImport } from './routes/index'

const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinasiRoute = DestinasiRouteImport.update({
  id: '/destinasi',
  path: '/destinasi',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraPemesananRoute = CaraPemesananRouteImport.update({
  id: '/cara-pemesanan',
  path: '/cara-pemesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmadaRoute = ArmadaRouteImport.update({
  id: '/armada',
  path: '/armada',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armada': typeof ArmadaRoute
  '/cara-pemesanan': typeof CaraPemesananRoute
  '/destinasi': typeof DestinasiRoute
  '/faq': typeof FaqRoute
  '/layanan': typeof LayananRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armada': typeof ArmadaRoute
  '/cara-pemesanan': typeof CaraPemesananRoute
  '/destinasi': typeof DestinasiRoute
  '/faq': typeof FaqRoute
  '/layanan': typeof LayananRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armada': typeof ArmadaRoute
  '/cara-pemesanan': typeof CaraPemesananRoute
  '/destinasi': typeof DestinasiRoute
  '/faq': typeof FaqRoute
  '/layanan': typeof LayananRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/armada'
    | '/cara-pemesanan'
    | '/destinasi'
    | '/faq'
    | '/layanan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armada' | '/cara-pemesanan' | '/destinasi' | '/faq' | '/layanan'
  id:
    | '__root__'
    | '/'
    | '/armada'
    | '/cara-pemesanan'
    | '/destinasi'
    | '/faq'
    | '/layanan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmadaRoute: typeof ArmadaRoute
  CaraPemesananRoute: typeof CaraPemesananRoute
  DestinasiRoute: typeof DestinasiRoute
  FaqRoute: typeof FaqRoute
  LayananRoute: typeof LayananRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinasi': {
      id: '/destinasi'
      path: '/destinasi'
      fullPath: '/destinasi'
      preLoaderRoute: typeof DestinasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-pemesanan': {
      id: '/cara-pemesanan'
      path: '/cara-pemesanan'
      fullPath: '/cara-pemesanan'
      preLoaderRoute: typeof CaraPemesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armada': {
      id: '/armada'
      path: '/armada'
      fullPath: '/armada'
      preLoaderRoute: typeof ArmadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmadaRoute: ArmadaRoute,
  CaraPemesananRoute: CaraPemesananRoute,
  DestinasiRoute: DestinasiRoute,
  FaqRoute: FaqRoute,
  LayananRoute: LayananRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
